#cloud-config
users:
 - name: "seca-dev"
   groups:
    - sudo
    - docker
  ssh-authorized-keys:
    - "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEA2KfXB4n6hpKwZ1Ku8yY1HinyXH4bFjVaP4zk6dPPESiyWTNygmJ1vfkvWL6hmHIbxUlk0azseWkXVJiJinsqhtIe7WIkCBPBSmAHKk0cUw3RXrQajWcLjlDdUAvthWM6uNQdn46e3gk0dJ+sTStqpyOzyxKDRecDEN3FpcxlBQxzJGEAYnAIgOshjLB+WQ7kyZJirhg5xvYe9D+WFKsZ9ca5N8ItgO0ZFDH4cY4KSGUOO29OsGFAK74f41jy0w6eUuLZa9WZe1IjawftOPVVyx14qTFT8W0jKXKzfg5T0rKy1+psenqVZCITt/kRv63Nl0zUiNnF47hFcr5maIcBMQ== "

